version: '2'
services:
    fpr360-app:
        image: fpr360
        environment:
            # - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://fpr360-postgresql:5432/fpr360
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    fpr360-postgresql:
        extends:
            file: postgresql.yml
            service: fpr360-postgresql
